# Generated by Django 3.2 on 2024-09-26 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_auto_20240926_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='thumbnail_base64',
            new_name='thumbnail',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='image_base64',
            new_name='image',
        ),
    ]
