# Generated by Django 3.2 on 2024-09-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0005_auto_20240926_1552'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='ProductType',
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'verbose_name_plural': 'Product_Types'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='product_type',
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('product_name', 'category', 'product_type'), name='unique_product_in_category_type'),
        ),
        migrations.AlterModelTable(
            name='producttype',
            table='product_types',
        ),
    ]
