# Generated by Django 3.2 on 2024-09-27 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0010_alter_product_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('restock_date', models.DateTimeField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='myadmin.product')),
            ],
            options={
                'verbose_name_plural': 'Stock',
                'db_table': 'stock',
            },
        ),
    ]
