# Generated by Django 3.2 on 2024-10-13 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0013_auto_20241013_1803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myusers',
            options={'verbose_name': 'MyUser', 'verbose_name_plural': 'MyUsers'},
        ),
    ]
