# Generated by Django 3.2 on 2024-10-15 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myadmin', '0014_alter_myusers_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myusers',
            options={},
        ),
        migrations.RenameField(
            model_name='myusers',
            old_name='date_joined',
            new_name='join_date',
        ),
        migrations.AlterField(
            model_name='myusers',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='myusers',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='myadmin_user_set', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='myusers',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='myadmin_user_set', to='auth.Permission'),
        ),
        migrations.AlterModelTable(
            name='myusers',
            table=None,
        ),
    ]
