# Generated by Django 3.2 on 2024-10-15 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0015_auto_20241015_1011'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='myusers',
            table='my_users',
        ),
    ]
