# Generated by Django 3.2 on 2024-10-15 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0016_alter_myusers_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusers',
            name='role_name',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin')], default='customer', max_length=50),
        ),
        migrations.AddField(
            model_name='myusers',
            name='user_picture',
            field=models.ImageField(blank=True, null=True, upload_to='user_pictures/'),
        ),
    ]
