# Generated by Django 3.2 on 2024-10-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0017_auto_20241015_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusers',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
