# Generated by Django 3.2 on 2024-10-20 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0022_auto_20241020_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_status',
        ),
    ]
